# Generated by Django 5.1.1 on 2024-09-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_transactions_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='current_amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='savings_amount',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='savings_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
