# Generated by Django 5.1.1 on 2024-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_remove_transactions_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='account_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
