# Generated by Django 5.1.1 on 2024-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_transactions_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
