# Generated by Django 5.1.1 on 2024-09-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_transactions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='current_amount',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='savings_amount',
            field=models.FloatField(default='0.0'),
        ),
    ]
